name: Delete Deployments
on: workflow_dispatch

permissions:
  contents: write
  deployments: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all deployments
        run: |
          for id in $(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/deployments | jq '.[].id'); do
            curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/deployments/$id
          done
